language: python
python:
- '3.6'
sudo: false
cache: pip
install: pip install sphinx
script: sphinx-build -nWT -b html . _build/html
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  local_dir: _build/html
  on:
    branch: master



